<a href="https://colab.research.google.com/github/ndb796/Python-Data-Analysis-and-Image-Processing-Tutorial/blob/master/03.%20Numpy%EC%9D%98%20%EA%B8%B0%EB%B3%B8%20%EC%82%AC%EC%9A%A9%EB%B2%95/Numpy%EC%9D%98%20%EA%B8%B0%EB%B3%B8%20%EC%82%AC%EC%9A%A9%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy의 기본 사용법
[강의 노트](https://github.com/ndb796/Python-Data-Analysis-and-Image-Processing-Tutorial/blob/master/04.%20Numpy%EC%9D%98%20%EC%97%B0%EC%82%B0%EA%B3%BC%20%ED%95%A8%EC%88%98/Python%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%EA%B3%BC%20%EC%9D%B4%EB%AF%B8%EC%A7%80%20%EC%B2%98%EB%A6%AC%20-%20Numpy%EC%9D%98%20%EC%97%B0%EC%82%B0%EA%B3%BC%20%ED%95%A8%EC%88%98.pdf)

Python의 Numpy 라이브러리는 List와 **상호 변환이 가능**합니다.

In [3]:
import numpy as np

array = np.array([1, 2, 3])
print(array.size) # 배열의 크기
print(array.dtype) # 배열 원소의 타입
print(array[2]) # 인덱스 2의 원소

3
int64
3


Python의 Numpy 라이브러리는 **다양한 형태의 배열**을 초기화 할 수 있습니다.

In [4]:
import numpy as np

# 0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

# 0으로 초기화
array2 = np.zeros((4, 4), dtype=float)
print(array2)

# 1로 초기화
array3 = np.ones((3, 3), dtype=str)
print(array3)

# 0부터 9까지 랜덤하게 초기화 된 배열 만들기
array4 = np.random.randint(0, 10, (3, 3))
print(array4)

# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0, 1, (3, 3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[9 7 8]
 [7 4 9]
 [2 4 3]]
[[ 1.20040659 -2.1623658  -1.40677179]
 [-2.6369517  -0.14826339 -0.07992751]
 [-1.11540671 -0.16563966  0.51126355]]


Numpy는 다양한 형태로 **합치기가 가능** 있습니다.

In [5]:
import numpy as np

array1 = np.array([1, 2, 3]) 
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


Numpy를 위 아래로 합칠 수 있습니다.

In [6]:
import numpy as np

array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)

print(array3.shape)
print(array3)

(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


Numpy의 **형태를 변경**할 수 있습니다.

In [7]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape((2, 2))
print(array2.shape)

(2, 2)


Numpy의 **형태를 나누기** 할 수 있습니다.

In [9]:
import numpy as np

array = np.arange(8).reshape(2, 4)
#[2]열을 기준으로 split
left, right = np.split(array, [2], axis=1)

print(left.shape)
print(right.shape)
print(right[1][1])

(2, 2)
(2, 2)
7
